# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_livecenteraccounts_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecenteraccounts',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='livecenteraccounts',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
