# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171218_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCenterSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=256)),
                ('session_value', models.CharField(max_length=256)),
                ('expire', models.IntegerField()),
            ],
        ),
    ]
