# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_livecentersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecentersession',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
