# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_livecentersession_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCenterTempKeyIdTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('key', models.CharField(max_length=256)),
                ('expire', models.IntegerField()),
            ],
        ),
    ]
